// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ServiceUserId } from './ServiceUser';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.application */
export type ApplicationId = string & { __brand: 'ApplicationId' };

/** Represents the table public.application */
export default interface ApplicationTable {
  id: ColumnType<ApplicationId, ApplicationId, ApplicationId>;

  owner_service_user_id: ColumnType<ServiceUserId, ServiceUserId, ServiceUserId>;

  name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Application = Selectable<ApplicationTable>;

export type NewApplication = Insertable<ApplicationTable>;

export type ApplicationUpdate = Updateable<ApplicationTable>;
