// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ServiceUserId } from './ServiceUser';
import { type ApplicationId } from './Application';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.application_api_key */
export type ApplicationApiKeyId = string & { __brand: 'ApplicationApiKeyId' };

/** Represents the table public.application_api_key */
export default interface ApplicationApiKeyTable {
  id: ColumnType<ApplicationApiKeyId, ApplicationApiKeyId, ApplicationApiKeyId>;

  owner_service_user_id: ColumnType<ServiceUserId, ServiceUserId, ServiceUserId>;

  scope_application_id: ColumnType<ApplicationId, ApplicationId, ApplicationId>;

  key: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type ApplicationApiKey = Selectable<ApplicationApiKeyTable>;

export type NewApplicationApiKey = Insertable<ApplicationApiKeyTable>;

export type ApplicationApiKeyUpdate = Updateable<ApplicationApiKeyTable>;
