// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ServiceUserId } from './ServiceUser';
import { type ApplicationId } from './Application';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.permission */
export type PermissionId = string & { __brand: 'PermissionId' };

/** Represents the table public.permission */
export default interface PermissionTable {
  id: ColumnType<PermissionId, PermissionId, PermissionId>;

  owner_service_user_id: ColumnType<ServiceUserId, ServiceUserId, ServiceUserId>;

  owner_application_id: ColumnType<ApplicationId, ApplicationId, ApplicationId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Permission = Selectable<PermissionTable>;

export type NewPermission = Insertable<PermissionTable>;

export type PermissionUpdate = Updateable<PermissionTable>;
