// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as ServiceUserTable } from './ServiceUser';
import { type default as SessionTable } from './Session';
import { type default as ApplicationTable } from './Application';
import { type default as ApplicationApiKeyTable } from './ApplicationApiKey';
import { type default as PermissionTable } from './Permission';
import { type default as RoleTable } from './Role';
import { type default as RolePermissionTable } from './RolePermission';
import { type default as UserTable } from './User';
import { type default as UserRoleTable } from './UserRole';

export default interface PublicSchema {
  service_user: ServiceUserTable;

  session: SessionTable;

  application: ApplicationTable;

  application_api_key: ApplicationApiKeyTable;

  permission: PermissionTable;

  role: RoleTable;

  role_permission: RolePermissionTable;

  user: UserTable;

  user_role: UserRoleTable;
}
