// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ServiceUserId } from './ServiceUser';
import { type ApplicationId } from './Application';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.role */
export type RoleId = string & { __brand: 'RoleId' };

/** Represents the table public.role */
export default interface RoleTable {
  id: ColumnType<RoleId, RoleId, RoleId>;

  owner_service_user_id: ColumnType<ServiceUserId, ServiceUserId, ServiceUserId>;

  owner_application_id: ColumnType<ApplicationId, ApplicationId, ApplicationId>;

  name: ColumnType<string, string, string>;

  description: ColumnType<string | null, string | null, string | null>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Role = Selectable<RoleTable>;

export type NewRole = Insertable<RoleTable>;

export type RoleUpdate = Updateable<RoleTable>;
