// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ServiceUserId } from './ServiceUser';
import { type ApplicationId } from './Application';
import { type RoleId } from './Role';
import { type PermissionId } from './Permission';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Represents the table public.role_permission */
export default interface RolePermissionTable {
  owner_service_user_id: ColumnType<ServiceUserId, ServiceUserId, ServiceUserId>;

  owner_application_id: ColumnType<ApplicationId, ApplicationId, ApplicationId>;

  role_id: ColumnType<RoleId, RoleId, RoleId>;

  permission_id: ColumnType<PermissionId, PermissionId, PermissionId>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type RolePermission = Selectable<RolePermissionTable>;

export type NewRolePermission = Insertable<RolePermissionTable>;

export type RolePermissionUpdate = Updateable<RolePermissionTable>;
