// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.service_user */
export type ServiceUserId = string & { __brand: 'ServiceUserId' };

/** Represents the table public.service_user */
export default interface ServiceUserTable {
  id: ColumnType<ServiceUserId, ServiceUserId, ServiceUserId>;

  email: ColumnType<string, string, string>;

  password_hash: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type ServiceUser = Selectable<ServiceUserTable>;

export type NewServiceUser = Insertable<ServiceUserTable>;

export type ServiceUserUpdate = Updateable<ServiceUserTable>;
