// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ServiceUserId } from './ServiceUser';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.session */
export type SessionId = string & { __brand: 'SessionId' };

/** Represents the table public.session */
export default interface SessionTable {
  id: ColumnType<SessionId, SessionId, SessionId>;

  service_user_id: ColumnType<ServiceUserId, ServiceUserId, ServiceUserId>;

  expires_at: ColumnType<Date, Date | string | undefined, Date | string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  deleted_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Session = Selectable<SessionTable>;

export type NewSession = Insertable<SessionTable>;

export type SessionUpdate = Updateable<SessionTable>;
